FROM rrmoreira57943/flexspend:base-tc

WORKDIR /app

# Install Docker CLI (Assuming a Debian/Ubuntu base image)
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get install -y docker-ce-cli

RUN echo "security.provider.13=org.bouncycastle.jce.provider.BouncyCastleProvider" >> /usr/lib/jvm/java-19-openjdk-amd64/conf/security/java.security

COPY lib-bft-smart /app/lib-bft-smart

COPY target/hyflexchain-jar-with-dependencies.jar /app/hyflexchain.jar

# ENTRYPOINT ["java", "-jar", "hyflexchain.jar"]
# tc qdisc add dev eth0 root netem rate 110mbit delay 75ms 20ms
# docker run --rm -it -h replica-x --network hyflexchain --cap-add NET_ADMIN teste