test:
  workers:
    number: 2
  rounds:

    - label: Submit 5000 Transactions 50 tps - BFT-SMaRt
      description: Submit BFT-SMaRt transactions
      # txDuration: 60
      txNumber: 5000
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: lib/benchmarks/CreateTransactionBftsmartWithSC.js

    - label: Submit 10000 Transactions 100 tps - BFT-SMaRt
      description: Submit BFT-SMaRt transactions
      # txDuration: 60
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: lib/benchmarks/CreateTransactionBftsmartWithSC.js

    # - label: Submit 20000 Transactions 200 tps - BFT-SMaRt
    #   description: Test description for transfering money between accounts.
    #   # txDuration: 60
    #   txNumber: 20000
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 200
    #   workload:
    #     module: lib/benchmarks/CreateTransactionBftsmartWithSC.js

    # - label: Submit 40000 Transactions 400 tps - BFT-SMaRt
    #   description: Test description for transfering money between accounts.
    #   # txDuration: 60
    #   txNumber: 40000
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 400
    #   workload:
    #     module: lib/benchmarks/CreateTransactionBftsmartWithSC.js

    # - label: Submit 80000 Transactions 800 tps - BFT-SMaRt
    #   description: Test description for transfering money between accounts.
    #   # txDuration: 60
    #   txNumber: 80000
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 800
    #   workload:
    #     module: lib/benchmarks/CreateTransactionBftsmartWithSC.js
  
# monitors:
#   resource:
#   - module: docker
#     options:
#       interval: 5
#       containers:
#       - /replica-0
#       - /replica-1
#       - /replica-2
#       - /replica-3
#       charting:
#         bar:
#           metrics: [Memory(avg), CPU%(avg)]
#         polar:
#           metrics: [all]
