test:
  workers:
    number: 2
  rounds:
    - label: Prepare System
      txNumber: 250
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: lib/benchmarks/CreateTransaction.js

    - label: Submit 5000 Transactions 50 tps
      description: Test description for transfering money between accounts.
      txNumber: 5000
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: lib/benchmarks/CreateTransaction.js

    - label: Submit 10000 Transactions 100 tps
      description: Test description for transfering money between accounts.
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: lib/benchmarks/CreateTransaction.js

    - label: Submit 20000 Transactions 200 tps
      description: Test description for transfering money between accounts.
      txNumber: 20000
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: lib/benchmarks/CreateTransaction.js

    - label: Submit 40000 Transactions 400 tps
      description: Test description for transfering money between accounts.
      txNumber: 40000
      rateControl:
        type: fixed-rate
        opts:
          tps: 400
      workload:
        module: lib/benchmarks/CreateTransaction.js
  
monitors:
  resource:
  - module: docker
    options:
      interval: 5
      containers:
      - /replica-0
      - /replica-1
      - /replica-2
      - /replica-3
