test:
  workers:
    number: 2
  rounds:
    - label: Prepare System
      txNumber: 250
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: lib/benchmarks/CreateTransaction.js

    - label: Submit Transactions 50 tps
      description: Test description for transfering money between accounts.
      txNumber: 5000
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: lib/benchmarks/CreateTransaction.js
  
monitors:
  resource:
  - module: docker
    options:
      interval: 5
      containers:
      - /replica-0
      - /replica-1
      - /replica-2
      - /replica-3
