test:
  workers:
    number: 4
  rounds:
    - label: Submit Transactions.
      txNumber: 5000
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: lib/benchmarks/CreateTransaction.js
